version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adh-app-dev
    command: >
      sh -c "
        cd python &&
        pip install -r requirements.txt &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        pg_dump -h db -U django adh > /workspace/db_dump.sql &&
        python manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - ./:/workspace:cached
    ports:
      - "8080:8080"
      - "5173:5173"
    environment:
      DATABASE_URL: postgres://django:password@db:5432/adh
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: adh
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
