# Generated by Django 5.2 on 2025-06-17 14:45

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard_Zone',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('hazard_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='id',
            new_name='incident_id',
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='id',
            new_name='waypoint_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('polizei', 'Polizei'), ('feuerwehr', 'Feuerwehr'), ('krankenhaus', 'Krankenhaus'), ('leuchtturm', 'Leuchtturm'), ('kritische_infrastruktur', 'Kritische Infrastruktur'), ('medizinische_einrichtung', 'Medizinische Einrichtung'), ('versogungstelle', 'Versorgungstelle'), ('sonstige', 'Sonstige')], default='sonstige', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
