# Generated by Django 5.2 on 2025-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hazard_zone_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard_zone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
