# Generated by Django 5.2 on 2025-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hazard_zone_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('policestation', 'Police Station'), ('firestation', 'Fire Station'), ('hospital', 'Hospital'), ('critical infrastructure', 'Critical Infrastructure'), ('medical facility', 'Medical Facility'), ('supply center', 'Supply Center'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
