# Generated by Django 5.2 on 2025-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_waypoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard_zone',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hazard_zone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
